# ConfigMap
# ConfigMap 资源对象使用key-value形式的键值对来配置数据
kind: ConfigMap
apiVersion: v1
metadata:
  name: cm-demo
  namespace: default
data:
  data.1: hello
  data.2: world
  config: |
    property.1=value-1
    property.2=value-2
    property.3=value-3
---
apiVersion: v1
kind: Pod
metadata:
  name: testcm1-pod
spec:
  containers:
    - name: testcm1
      image: busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:    # 表示DB_HOST的值是与名称为"cm-demo"的ConfigMap中的KEY=db.host关联
              name: cm-demo
              key: db.host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: cm-demo
              key: db.port
      envFrom:
        - configMapRef:
            name: cm-demo